const questions = [
    {
        id: 1,
        domain: 'Computer Science',
        questionText: 'What does HTML stand for?',
        answerOptions: [
            { answerID: 'a', answerText: 'Hyper Text Markup Language'},
            { answerID: 'b', answerText: 'Hyperlinks and Text Markup Language'},
            { answerID: 'c', answerText: 'Home Tool Markup Language'},
            { answerID: 'd', answerText: 'Hyper Text Makeup Language'},
        ],
        correctResponse: 'a',
        questionRationale: 'HTML stands for Hyper Text Markup Language, which is the standard markup language for creating web pages and web applications.',
    },
    {
        id: 2,
        domain: 'Computer Science',
        questionText: 'What is the main purpose of CSS?',
        answerOptions: [
            { answerID: 'a', answerText: 'To define the structure of a web page'},
            { answerID: 'b', answerText: 'To provide interactivity on a web page'},
            { answerID: 'c', answerText: 'To style the appearance of a web page'},
            { answerID: 'd', answerText: 'To handle server-side logic'},
        ],
        correctResponse: 'c',
        questionRationale: 'CSS (Cascading Style Sheets) is used to style the appearance of a web page, including elements such as layout, colors, and fonts.',
    },
    {
        id: 3,
        domain: 'Computer Science',
        questionText: 'What does CSS stand for?',
        answerOptions: [
            { answerID: 'a', answerText: 'Cascading Style Sheet'},
            { answerID: 'b', answerText: 'Computer Style Sheet'},
            { answerID: 'c', answerText: 'Colorful Style Sheet'},
            { answerID: 'd', answerText: 'Creative Style Sheet'},
        ],
        correctResponse: 'a',
        questionRationale: 'CSS stands for Cascading Style Sheet, which is used for styling the appearance of web pages.',
    },
    {
        id: 4,
        domain: 'Computer Science',
        questionText: 'What is the purpose of JavaScript in web development?',
        answerOptions: [
            { answerID: 'a', answerText: 'To define the structure of a web page'},
            { answerID: 'b', answerText: 'To style the appearance of a web page'},
            { answerID: 'c', answerText: 'To provide interactivity on a web page'},
            { answerID: 'd', answerText: 'To handle server-side logic'},
        ],
        correctResponse: 'c',
        questionRationale: 'JavaScript is used to provide interactivity on a web page, including features such as dynamic content, user interaction, and form validation.',
    },
    {
        id: 5,
        domain: 'Computer Science',
        questionText: 'Which of the following is not a programming language?',
        answerOptions: [
            { answerID: 'a', answerText: 'Java'},
            { answerID: 'b', answerText: 'HTML'},
            { answerID: 'c', answerText: 'Python'},
            { answerID: 'd', answerText: 'C++'},
        ],
        correctResponse: 'b',
        questionRationale: 'HTML (Hyper Text Markup Language) is not a programming language; it is a markup language used for creating the structure of web pages.',
    },
    {
        id: 6,
        domain: 'Computer Science',
        questionText: 'Which programming language is often used for developing mobile applications?',
        answerOptions: [
            { answerID: 'a', answerText: 'Java'},
            { answerID: 'b', answerText: 'C#'},
            { answerID: 'c', answerText: 'Swift'},
            { answerID: 'd', answerText: 'All of the above'},
        ],
        correctResponse: 'd',
        questionRationale: 'Java (for Android), Swift (for iOS), and C# (for Windows Phone) are all commonly used programming languages for developing mobile applications.',
    },
    {
        id: 7,
        domain: 'Computer Science',
        questionText: 'What is the primary function of an operating system?',
        answerOptions: [
            { answerID: 'a', answerText: 'To provide a graphical user interface (GUI)'},
            { answerID: 'b', answerText: 'To manage hardware resources'},
            { answerID: 'c', answerText: 'To develop software applications'},
            { answerID: 'd', answerText: 'To connect to the internet'},
        ],
        correctResponse: 'b',
        questionRationale: 'The primary function of an operating system is to manage hardware resources, including memory, processors, storage devices, and input/output devices.',
    },
    {
        id: 8,
        domain: 'Computer Science',
        questionText: 'What is an algorithm?',
        answerOptions: [
            { answerID: 'a', answerText: 'A type of computer virus'},
            { answerID: 'b', answerText: 'A step-by-step procedure for solving a problem'},
            { answerID: 'c', answerText: 'A programming language'},
            { answerID: 'd', answerText: 'A hardware component'},
        ],
        correctResponse: 'b',
        questionRationale: 'An algorithm is a step-by-step procedure for solving a problem, often expressed as a sequence of instructions or a set of rules to follow.',
    },
    {
        id: 9,
        domain: 'Computer Science',
        questionText: 'What is the binary number system based on?',
        answerOptions: [
            { answerID: 'a', answerText: 'Base 2'},
            { answerID: 'b', answerText: 'Base 8'},
            { answerID: 'c', answerText: 'Base 10'},
            { answerID: 'd', answerText: 'Base 16'},
        ],
        correctResponse: 'a',
        questionRationale: 'The binary number system is based on base 2, meaning it uses only two digits: 0 and 1.',
    },
    {
        id: 10,
        domain: 'Computer Science',
        questionText: 'What is a variable in programming?',
        answerOptions: [
            { answerID: 'a', answerText: 'A constant value'},
            { answerID: 'b', answerText: 'A data type'},
            { answerID: 'c', answerText: 'A named storage location for data'},
            { answerID: 'd', answerText: 'A mathematical operation'},
        ],
        correctResponse: 'c',
        questionRationale: 'A variable in programming is a named storage location for data that can hold different values during the execution of a program.',
    },
    {
        id: 11,
        domain: 'Computer Science',
        questionText: 'What is the purpose of a loop in programming?',
        answerOptions: [
            { answerID: 'a', answerText: 'To store data temporarily'},
            { answerID: 'b', answerText: 'To define the structure of a web page'},
            { answerID: 'c', answerText: 'To execute a block of code repeatedly'},
            { answerID: 'd', answerText: 'To perform mathematical calculations'},
        ],
        correctResponse: 'c',
        questionRationale: 'A loop in programming is used to execute a block of code repeatedly until a certain condition is met.',
    },
    {
        id: 12,
        domain: 'Computer Science',
        questionText: 'What is the purpose of a function in programming?',
        answerOptions: [
            { answerID: 'a', answerText: 'To define the structure of a web page'},
            { answerID: 'b', answerText: 'To provide interactivity on a web page'},
            { answerID: 'c', answerText: 'To execute a block of code repeatedly'},
            { answerID: 'd', answerText: 'To organize and reuse code'},
        ],
        correctResponse: 'd',
        questionRationale: 'A function in programming is a reusable block of code that performs a specific task. Functions help organize code and promote code reusability.',
    },
    {
        id: 13,
        domain: 'Computer Science',
        questionText: 'What does CPU stand for?',
        answerOptions: [
            { answerID: 'a', answerText: 'Computer Processor Unit'},
            { answerID: 'b', answerText: 'Central Processing Unit'},
            { answerID: 'c', answerText: 'Computer Peripheral Unit'},
            { answerID: 'd', answerText: 'Central Peripheral Unit'},
        ],
        correctResponse: 'b',
        questionRationale: 'CPU stands for Central Processing Unit, which is the primary component of a computer responsible for executing instructions and performing calculations.',
    },
    {
        id: 14,
        domain: 'Computer Science',
        questionText: 'What is an IP address?',
        answerOptions: [
            { answerID: 'a', answerText: 'A unique identifier for a computer or device on a network'},
            { answerID: 'b', answerText: 'An internet browser'},
            { answerID: 'c', answerText: 'A type of programming language'},
            { answerID: 'd', answerText: 'A computer virus'},
        ],
        correctResponse: 'a',
        questionRationale: 'An IP address (Internet Protocol address) is a unique identifier assigned to each device connected to a computer network that uses the Internet Protocol for communication.',
    },
    {
        id: 15,
        domain: 'Computer Science',
        questionText: 'What is the purpose of a database?',
        answerOptions: [
            { answerID: 'a', answerText: 'To create web pages'},
            { answerID: 'b', answerText: 'To manage and store data'},
            { answerID: 'c', answerText: 'To provide interactivity on a web page'},
            { answerID: 'd', answerText: 'To design user interfaces'},
        ],
        correctResponse: 'b',
        questionRationale: 'A database is a structured collection of data that is used to manage and store information, allowing it to be easily accessed, managed, and updated.',
    },
    {
        id: 16,
        domain: 'Computer Science',
        questionText: 'What is the purpose of version control software?',
        answerOptions: [
            { answerID: 'a', answerText: 'To provide security for computer systems'},
            { answerID: 'b', answerText: 'To manage and track changes to files and code'},
            { answerID: 'c', answerText: 'To create and edit images and graphics'},
            { answerID: 'd', answerText: 'To optimize computer performance'},
        ],
        correctResponse: 'b',
        questionRationale: 'Version control software is used to manage and track changes to files and code, allowing multiple developers to collaborate on projects and maintain a history of changes.',
    },
    {
        id: 17,
        domain: 'Computer Science',
        questionText: 'What is the purpose of object-oriented programming (OOP)?',
        answerOptions: [
            { answerID: 'a', answerText: 'To manage hardware resources'},
            { answerID: 'b', answerText: 'To develop software applications'},
            { answerID: 'c', answerText: 'To provide interactivity on a web page'},
            { answerID: 'd', answerText: 'To organize and structure code based on objects'},
        ],
        correctResponse: 'd',
        questionRationale: 'Object-oriented programming (OOP) is a programming paradigm that organizes code based on objects, which are instances of classes that contain both data and methods.',
    },
    {
        id: 18,
        domain: 'Computer Science',
        questionText: 'What is the purpose of a firewall?',
        answerOptions: [
            { answerID: 'a', answerText: 'To provide interactivity on a web page'},
            { answerID: 'b', answerText: 'To manage and store data'},
            { answerID: 'c', answerText: 'To protect computer networks from unauthorized access'},
            { answerID: 'd', answerText: 'To execute a block of code repeatedly'},
        ],
        correctResponse: 'c',
        questionRationale: 'A firewall is a network security device that monitors and controls incoming and outgoing network traffic based on predetermined security rules, helping to protect computer networks from unauthorized access and cyberattacks.',
    },
    {
        id: 19,
        domain: 'Computer Science',
        questionText: 'What is the purpose of a compiler?',
        answerOptions: [
            { answerID: 'a', answerText: 'To provide interactivity on a web page'},
            { answerID: 'b', answerText: 'To manage and store data'},
            { answerID: 'c', answerText: 'To translate source code into machine code'},
            { answerID: 'd', answerText: 'To execute a block of code repeatedly'},
        ],
        correctResponse: 'c',
        questionRationale: 'A compiler is a software program that translates source code written in a high-level programming language into machine code that can be executed by a computer processor.',
    },
    {
        id: 20,
        domain: 'Computer Science',
        questionText: 'What is the purpose of encryption?',
        answerOptions: [
            { answerID: 'a', answerText: 'To provide interactivity on a web page'},
            { answerID: 'b', answerText: 'To manage and store data'},
            { answerID: 'c', answerText: 'To protect sensitive information by converting it into a coded format'},
            { answerID: 'd', answerText: 'To optimize computer performance'},
        ],
        correctResponse: 'c',
        questionRationale: 'Encryption is the process of converting data into a coded format that can only be read or understood by authorized parties, helping to protect sensitive information from unauthorized access.',
    },
    // Add more questions here
];

export default questions;
